CREATE TABLE PINYIN (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    SHENGMU TEXT,
    YUNMU TEXT NOT NULL,
    DIAO INT NOT NULL
);
CREATE INDEX PINYIN_INDEX_ZI ON PINYIN(ZI);

CREATE TABLE JYUTPING (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    SHENGMU TEXT,
    YUNMU TEXT NOT NULL,
    YUNWEI TEXT,
    DIAO INT NOT NULL
);
CREATE INDEX JYUTPING_INDEX_ZI ON JYUTPING(ZI);

CREATE TABLE CHAIZI(
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    CHAI TEXT NOT NULL,
    XU INT NOT NULL
);
CREATE INDEX CHAIZI_INDEX_ZI_XU ON CHAIZI(ZI,XU);

CREATE TABLE BIHUA (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT UNIQUE NOT NULL,
    BIHUA INT NOT NULL
);
CREATE INDEX BIHUA_INDEX_ZI_BIHUA ON BIHUA(ZI,BIHUA);

CREATE TABLE ZIPIN (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    PINLV TEXT NOT NULL
);
CREATE INDEX ZIPIN_INDEX_ZI_PINLV ON ZIPIN(ZI,PINLV);

CREATE TABLE BIANTI (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    LEIXING TEXT NOT NULL,
    BIANTI TEXT NOT NULL
);
CREATE INDEX BIANTI_INDEX_ZI_LEIXING ON BIANTI(ZI,LEIXING);

CREATE TABLE DEFINITION (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    DEFINITION TEXT NOT NULL
);
CREATE INDEX DEFINITION_INDEX_ZI ON DEFINITION(ZI);

CREATE TABLE KANGXI (
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    JUAN TEXT NOT NULL,
    BU TEXT NOT NULL,
    YE TEXT NOT NULL,
    YI TEXT NOT NULL
);
CREATE INDEX KANGXI_INDEX_ZI ON KANGXI(ZI);

CREATE TABLE CIYU (
    ID INTEGER PRIMARY KEY NOT NULL,
    CI TEXT NOT NULL,
    PINYIN TEXT,
    YI TEXT,
    YUAN TEXT,
    LI TEXT
);
CREATE INDEX CIYU_INDEX_CI ON CIYU(CI);

CREATE TABLE SHUZI(
    ID INTEGER PRIMARY KEY NOT NULL,
    ZI TEXT NOT NULL,
    LEIXING TEXT NOT NULL,
    SHU INT
);
CREATE INDEX SHUZI_INDEX_ZI ON SHUZI(ZI);

CREATE TABLE XIEHOUYU (
    ID INTEGER PRIMARY KEY NOT NULL,
    XIEHOUYU TEXT NOT NULL,
    JIESHI TEXT NOT NULL
);
